// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAq9hUyhq6auyDEfKrBaqZFJldyVjdSj-0',
    appId: '1:135892819944:web:3cc82270e8b7841b584e5d',
    messagingSenderId: '135892819944',
    projectId: 'chatfirebase-b9bfb',
    authDomain: 'chatfirebase-b9bfb.firebaseapp.com',
    storageBucket: 'chatfirebase-b9bfb.appspot.com',
    measurementId: 'G-D83EVYN86N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9MS0lqIoAaQiQYbrVB8li1RAVgOaxURM',
    appId: '1:135892819944:android:2418be4fcf860689584e5d',
    messagingSenderId: '135892819944',
    projectId: 'chatfirebase-b9bfb',
    storageBucket: 'chatfirebase-b9bfb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWDh0gYlL1e8etWta_cyPQ_Gz9rCFRsO8',
    appId: '1:135892819944:ios:70e041fd2908d1f9584e5d',
    messagingSenderId: '135892819944',
    projectId: 'chatfirebase-b9bfb',
    storageBucket: 'chatfirebase-b9bfb.appspot.com',
    iosClientId: '135892819944-1mg1mvsnubdjlnqio1egftvs0g8201tr.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWDh0gYlL1e8etWta_cyPQ_Gz9rCFRsO8',
    appId: '1:135892819944:ios:70e041fd2908d1f9584e5d',
    messagingSenderId: '135892819944',
    projectId: 'chatfirebase-b9bfb',
    storageBucket: 'chatfirebase-b9bfb.appspot.com',
    iosClientId: '135892819944-1mg1mvsnubdjlnqio1egftvs0g8201tr.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseChat',
  );
}
